secure password added to merchant
BorsukMorski/Minimarket-Team-A pull request #6
Opened 2018-05-21 13:30 UTC by neciai

2018-05-31 14:16 UTC, karolinab requested changes
Wygląda ekstra 👍 Jedna ważna rzecz do zastanowienia z resztą grupy, żeby aplikacja działała sprawnie :)

2018-05-31 14:16 UTC, karolinab commented on app/controllers/application_controller.rb
> +  before_action :require_valid_merchant!
Ta metoda (callback) powinna być wywoływana, jedynie w momencie, gdy próbujemy się dostać do części handlarza. Diała to w porządku teraz, bo mamy jedynie jeden widok, ale co będzie gdy dodamy możliwość logowania klienta? Zawsze będzie przekierowanie do logowania dla handlarza. Gdy pojawią się nowe widoki np. dodawanie produktu, należałoby przenieść ten callback do odpowiednich controllerów. Zastanówcie się, do której części aplikacji dostęp powinien mieć jedynie zalogowany handlarz, a które są dostępne dla wszystkich (np. strona główna). Sama metoda działa super :) !

2018-05-31 14:16 UTC, karolinab commented on app/controllers/dashboard_controller.rb
> +  def show
Ciekawostka: jeśli akcja i nazwa renderowanego widoku są zgodne z ogólną konwencją railsów (czyli dla akcji i 'dashboard/show'  renderujemy widok z : 'views/dashboards/show.html.erb' ), można usunąć tą pustą metodę :) Oczywiście możecie zostawić tak jak jest.

2018-05-31 14:16 UTC, karolinab commented on app/views/layouts/application.html.erb
> +    <title>AuthenticationExample</title>
Czy na pewno chcemy zmienić tytuł strony ;)?

2018-05-31 14:16 UTC, karolinab commented on app/views/merchants/create.html.erb
> +<p>Find me in app/views/merchants/create.html.erb</p>
Widok do usunięcia, nigdy nie używany.

2018-06-01 08:42 UTC, neciai commented on app/views/layouts/application.html.erb
> +    <title>AuthenticationExample</title>
Nie chcemy ;) tylko właśnie nie wiem jak to teraz sprawnie zmienić, żeby z powrotem było MinimarketTeamA

2018-06-04 18:10 UTC, merged