Customer authentication
BorsukMorski/Minimarket-Team-A pull request #7
Opened 2018-05-27 13:18 UTC by BorsukMorski

2018-05-29 21:57 UTC, basial reviewed
Bardzo bliziutko 🎉 Uwaga ogólna -

- Zwracajcie proszę uwagę na formatowanie kodu, może wydawać się mało istotne, ale jest wręcz przeciwnie :wink: Tutaj ogólny style guide https://github.com/bbatsov/ruby-style-guide, ale dla Was na razie najważniejsze - 1) wcięcia kolejno zagnieżdżonych linii na dwie spacje, 2) brak randomowych enterków

I bardziej szczegółowe -
- Może warto by było ustawić dashboard#show jako root? http://guides.rubyonrails.org/routing.html#using-root Tym sposobem po zalogowaniu nie trafimy na ekran `Yay! You’re on Rails!` tylko do naszego dashboardu
- Nie mamy nigdzie linka do wylogowania, right? Można by pomyśleć o uzależnienu tego co się wyświetla na dashboardowym show od tego czy customer jest zalogowany (jeśli zalogowany - link fo wylogowania, jeśli niezalogowany - link do rejestracji lub logowania)

2018-05-29 21:57 UTC, basial commented on app/controllers/customers_controller.rb
> +	    session[:customer_id] = @Customer.id
Czy Wasza zmienna na pewno nazywa się `@Customer`? 😉

2018-06-10 12:56 UTC, BorsukMorski commented
Poprosimy o feedback do zmerdzowanych customerów i merchantów...

2018-06-12 07:07 UTC, karolinab requested changes

2018-06-12 07:07 UTC, karolinab commented on app/assets/stylesheets/sessions.scss
> +>>>>>>> master
Pozostałości po mergu, trzeba na to uważać i pousuwać :)

2018-06-12 07:07 UTC, karolinab commented on app/controllers/application_controller.rb
> +    @current_customer ||= Customer.find(c_session[:customer_id]) if c_session[:customer_id]
c_session -> session

2018-06-12 07:07 UTC, karolinab commented on app/controllers/application_controller.rb
> +    if !m_session[:merchant_id].blank?
m_session -> session

2018-06-18 17:48 UTC, karolinab approved these changes

2018-06-18 17:52 UTC, merged